import { Component } from '@angular/core';
import { EvtConfigService } from 'src/app/services/evt-config.service';
import { map } from 'rxjs/operators';

@Component({
  selector: 'app-auto-generated-content-config',
  templateUrl: './auto-generated-content-config.component.html',
  styleUrls: ['./auto-generated-content-config.component.scss']
})
export class AutoGeneratedContentConfigComponent {
  configs$ = this.evtConfigService.configs$.pipe(
    map(c => c.advanced)
  );

  constructor(
    private evtConfigService: EvtConfigService,
  ) {
  }
}
