import { Component, ViewChild, ElementRef, AfterViewInit, Output, EventEmitter, AfterContentInit } from '@angular/core';

@Component({
  selector: 'app-advanced-configs',
  templateUrl: './advanced-configs.component.html',
  styleUrls: ['./advanced-configs.component.scss']
})
export class AdvancedConfigsComponent implements AfterViewInit {
  @ViewChild('pathParameters', { static: true }) pathParametersElement: ElementRef;
  @ViewChild('autoGeneratedContent', { static: true }) autoGeneratedContentElement: ElementRef;
  @ViewChild('xpathExpressions', { static: true }) xpathExpressionsElement: ElementRef;

  @Output() sectionInit: EventEmitter<AdvancedConfigsInit> = new EventEmitter();

  ngAfterViewInit() {
    this.sectionInit.emit({
      pathParametersOffset: this.pathParametersElement.nativeElement.offsetTop,
      autoGeneratedContentOffset: this.autoGeneratedContentElement.nativeElement.offsetTop,
      xpathExpressionsOffset: this.xpathExpressionsElement.nativeElement.offsetTop
    });
  }

}

export interface AdvancedConfigsInit {
  pathParametersOffset: number;
  autoGeneratedContentOffset: number;
  xpathExpressionsOffset: number;
}
