import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.scss']
})
export class DashboardComponent implements OnInit {
  public sections: ConfigParamsSection[] = [{
    name: 'mainData',
    items: [
      { name: 'editionMainInfo' },
      { name: 'editionLevels' },
      { name: 'additionalContent' },
      { name: 'dataFormat' }
    ]
  }, {
    name: 'tools',
    items: [
      { name: 'imageTools' },
      { name: 'navigation' },
      { name: 'views' },
      { name: 'prefatoryMatter' },
      { name: 'search' },
      { name: 'listsNE' },
      { name: 'viscoll' },
      { name: 'poetry' }
    ]
  }, {
    name: 'advanced',
    items: [
      { name: 'pathParameters' },
      { name: 'autoGeneratedContent' },
      { name: 'xpathExpressions' }
    ]
  }];
  constructor() { }

  ngOnInit() {
  }

}

interface ConfigParamsSection {
  name: string;
  items: ConfigParamGroup[];
}

interface ConfigParamGroup {
  name: string;
}

